# Generated by Django 5.2.1 on 2025-06-03 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_mockpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockpayment',
            name='booking',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='bookings.booking'),
        ),
    ]
